/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DatadeskRouteImport } from './routes/datadesk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorDiagramIdRouteImport } from './routes/editor.$diagramId'

const DatadeskRoute = DatadeskRouteImport.update({
  id: '/datadesk',
  path: '/datadesk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorDiagramIdRoute = EditorDiagramIdRouteImport.update({
  id: '/editor/$diagramId',
  path: '/editor/$diagramId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datadesk': typeof DatadeskRoute
  '/editor/$diagramId': typeof EditorDiagramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datadesk': typeof DatadeskRoute
  '/editor/$diagramId': typeof EditorDiagramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datadesk': typeof DatadeskRoute
  '/editor/$diagramId': typeof EditorDiagramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/datadesk' | '/editor/$diagramId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/datadesk' | '/editor/$diagramId'
  id: '__root__' | '/' | '/datadesk' | '/editor/$diagramId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatadeskRoute: typeof DatadeskRoute
  EditorDiagramIdRoute: typeof EditorDiagramIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/datadesk': {
      id: '/datadesk'
      path: '/datadesk'
      fullPath: '/datadesk'
      preLoaderRoute: typeof DatadeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$diagramId': {
      id: '/editor/$diagramId'
      path: '/editor/$diagramId'
      fullPath: '/editor/$diagramId'
      preLoaderRoute: typeof EditorDiagramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatadeskRoute: DatadeskRoute,
  EditorDiagramIdRoute: EditorDiagramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
